def generate_welcome_html():
    html = [
        "<!DOCTYPE html>",
        "<html lang='es'>",
        "<head>",
        "    <meta charset='UTF-8'>",
        "    <title>Bienvenido a SpectrOCR</title>",
        "    <style>",
        "        body { font-family: 'Segoe UI', Arial, sans-serif; margin: 30px; background-color: #f8f9fa; color: #333; line-height: 1.6; }",
        "        .container { max-width: 600px; margin: 0 auto; background: white; padding: 30px; border-radius: 12px; box-shadow: 0 4px 15px rgba(0,0,0,0.1); }",
        "        h1 { color: #2c3e50; border-bottom: 2px solid #3498db; padding-bottom: 10px; margin-top: 0; }",
        "        p { margin-bottom: 20px; }",
        "        .row { margin-bottom: 20px; }",
        "        label { font-weight: bold; display: block; margin-bottom: 8px; }",
        "        input[type='text'], input[type='password'] { width: 100%; padding: 12px; border: 2px solid #ddd; border-radius: 6px; box-sizing: border-box; font-size: 1em; }",
        "        input:focus { border-color: #3498db; outline: none; }",
        "        button { background-color: #27ae60; color: white; border: none; padding: 12px 40px; border-radius: 6px; cursor: pointer; font-weight: bold; font-size: 1.1em; width: 100%; transition: background 0.3s; }",
        "        button:hover { background-color: #219150; }",
        "        a { color: #3498db; text-decoration: none; font-weight: bold; }",
        "        a:hover { text-decoration: underline; }",
        "    </style>",
        "    <script>",
        "       function sendWelcomeData() {",
        "           var name = document.getElementById('api_name').value.trim();",
        "           var key = document.getElementById('api_key').value.trim();",
        "           if (!key) { alert('Por favor, ingresá una clave API Key para continuar.'); return; }",
        "           ",
        "           // Evitar URLSearchParams por compatibilidad con backends viejos",
        "           var query = 'name=' + encodeURIComponent(name || 'Clave Principal') + '&key=' + encodeURIComponent(key);",
        "           window.location.href = 'app://welcome/save?' + query;",
        "       }",
        "    </script>",
        "</head>",
        "<body>",
        "    <div class='container'>",
        "        <h1>¡Hola! Bienvenido a SpectrOCR</h1>",
        "        <p>Este programa está pensado para que, con suerte, logres navegar por programas antaño inaccesibles.</p>",
        "        <p>Para que funcione correctamente, necesitarás colocar una clave API de Google abajo. La podés conseguir desde <a href='https://aistudio.google.com/apikey'>Google AI Studio</a>.</p>",
        "        <p>Una vez pongas la API, este cuadro se cerrará y el programa trabajará en segundo plano, a menos que invoques las configuraciones (Control + Shift + O).</p>",
        "        ",
        "        <div class='row'>",
        "            <label for='api_name'>Nombre para identificar esta clave (opcional)</label>",
        "            <input type='text' id='api_name' placeholder='Ej: Mi clave personal' aria-label='Nombre descriptivo para la API Key'>",
        "        </div>",
        "        ",
        "        <div class='row'>",
        "            <label for='api_key'>Tu API Key de Gemini</label>",
        "            <input type='password' id='api_key' placeholder='Pegá acá tu AIzaSy...' aria-label='Clave API de Google AI Studio'>",
        "        </div>",
        "        ",
        "        <p style='font-size: 0.96em; color: #555; background: #e8f4fd; padding: 10px; border-radius: 6px;'>",
        "            <strong>Nota:</strong> Al presionar comenzar, verificaremos tu clave con los servidores de Google. Es normal experimentar un pequeño retraso de uno o dos segundos.",
        "        </p>",
        "        ",
        "        <button onclick='sendWelcomeData()'>Comenzar</button>",
        "    </div>",
        "</body>",
        "</html>"
    ]
    return "\n".join(html)
